# Site Settings
title: Photo Organizer
description: Intelligent desktop app for organizing photos and videos. Automatic sorting, duplicate detection, and privacy-focused local processing for Windows and macOS.
author: Maurits van Hassel

# URL Settings
url: "https://organizer.flipfocus.nl"
baseurl: ""

# Build Settings
markdown: kramdown

# SEO Plugins (if you want to add jekyll-seo-tag in the future)
plugins:
  - jekyll-sitemap

# PWA/Manifest Settings
pwa:
  name: "Photo Organizer"
  short_name: "Photo Organizer"
  theme_color: "#2563eb" # blue-600
  background_color: "#ffffff"
  display: "standalone"
  start_url: "/"
  icons:
    - src: "/assets/favicon/favicon195.png"
      sizes: "195x195"
      type: "image/png"
    - src: "/assets/favicon/app.ico"
      sizes: "256x256"
      type: "image/ico"

# SEO Settings
lang: en
keywords: photo organizer, photo management, image organization, photo sorting, picture organizer, media management, photo library, offline photo organizer, privacy-focused, desktop app, Windows, macOS, duplicate detection, EXIF data, automatic sorting

# Social Media and Business Info
social:
  github: "mcvanhassel/photo-organizer.app"

# Business/App Information for Rich Snippets
app:
  name: "Photo Organizer"
  price: "19.99"
  currency: "EUR"
  platforms: ["macOS", "Windows"]
  category: "Productivity"

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json
  - tailwind.config.js

# Include directories and files
include:
  - assets
  - _site/assets
